from __future__ import annotations

import unittest

from tools.classcodex_cli import render_stat_dr_lua


class RenderStatDrLuaTests(unittest.TestCase):
    def test_wraps_the_raw_source_with_a_generated_file_banner(self) -> None:
        source = 'local _, ns = ...\nns.StatDR = {}\nfunction ns.StatDR.RawPercentFor(x) return x end\n'
        rendered = render_stat_dr_lua(source)
        self.assertIn("-- Generated by tools/classcodex_cli.py", rendered)
        self.assertIn("Do not edit manually", rendered)
        self.assertIn("function ns.StatDR.RawPercentFor(x) return x end", rendered)

    def test_preserves_the_source_verbatim_after_the_banner(self) -> None:
        source = 'local _, ns = ...\nns.StatDR = { ready = true }\n'
        rendered = render_stat_dr_lua(source)
        self.assertTrue(rendered.endswith(source))


if __name__ == "__main__":
    unittest.main()
