#!/usr/bin/env python3
"""Fetch the live ClassCodex build (from the same public build host the
official Icy Veins / U.GG desktop app updates from) and write its stat
diminishing-returns module as the addon's SV_StatDR.lua.

The per-spec ClassCodex data itself is not written here: the stat targets and
weights pipelines (tools/classcodex_targets_cli.py, classcodex_weights_cli.py)
fetch and build it themselves, and the addon reads only their output.
`--report` still prints a per-spec source summary of that data.

Replaces the abandoned Scraper repo (github.com/ElaNte75/Scraper), which
pulled from a third-party GitHub mirror now confirmed frozen and stale.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from tools.classcodex_build import build, build_stat_dr
    from tools.classcodex_fetch import FetchFailure, fetch_all
except ModuleNotFoundError:
    # Run as "python tools/classcodex_cli.py": sys.path[0] is tools/, not the repo root.
    from classcodex_build import build, build_stat_dr
    from classcodex_fetch import FetchFailure, fetch_all

STAT_DR_MAX_FILE_BYTES = 1 * 1024 * 1024


def render_stat_dr_lua(source: str) -> str:
    banner = (
        "-- Generated by tools/classcodex_cli.py from the live ClassCodex build.\n"
        "-- Vendored as real Lua source (not re-serialized data) because it\n"
        "-- defines functions, not just tables. Do not edit manually.\n\n"
    )
    return banner + source


def write_stat_dr_file(source: str, path: Path) -> int:
    text = render_stat_dr_lua(source)
    size = len(text.encode("utf-8"))
    if size > STAT_DR_MAX_FILE_BYTES:
        raise ValueError(f"StatDR file is {size} bytes, over the {STAT_DR_MAX_FILE_BYTES} byte limit")
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_bytes(text.encode("utf-8"))
    tmp.replace(path)
    return size


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("StatVerdict/Data/Generated/SV_StatDR.lua"))
    parser.add_argument("--report", action="store_true", help="print a short per-spec summary and write nothing")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    try:
        fetched = fetch_all()
    except FetchFailure as exc:
        print(f"Refusing to write: {exc}", file=sys.stderr)
        return 1

    if args.report:
        specs = build(fetched.sources)
        for spec_key in sorted(specs):
            fields = specs[spec_key]
            sources = ",".join(f"{name}:{fields[name]['source']}" for name in sorted(fields))
            print(f"{spec_key}: {sources}")
        print(f"build {fetched.build_id} ({fetched.published_at}), {len(specs)} specs")
        return 0

    try:
        build_stat_dr(fetched.sources["stat_dr"])
    except Exception as exc:  # noqa: BLE001 - fail closed on any parse problem
        print(f"Refusing to write: StatDR.lua failed to parse ({exc})", file=sys.stderr)
        return 1

    size = write_stat_dr_file(fetched.sources["stat_dr"], args.out)
    print(f"Wrote {args.out} ({size} bytes, build {fetched.build_id})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
