#!/usr/bin/env python3
"""Fetches live ClassCodex data and writes the per-goal SimC-reconstructed
stat-target file the addon will eventually read (StatVerdict/Core/*.lua
wiring is a separate, later plan)."""
from __future__ import annotations

import argparse
import functools
import sys
from pathlib import Path
from typing import Any

try:
    from tools.classcodex_build import build
    from tools.classcodex_fetch import FetchFailure, fetch_all
    from tools.classcodex_targets import (
        DEFAULT_MIN_COVERAGE_RATIO,
        SkipRecord,
        build_all,
        format_coverage_report,
        format_rating_sanity,
        format_skip_summary,
        gate_and_write,
    )
    from tools.lua_render import to_lua_compact
    from tools.upgrade_tracks import load_track_swap
    from tools.wowhead_stat_engine import TooltipCache, reconstruct_loadout
except ModuleNotFoundError:
    from classcodex_build import build
    from classcodex_fetch import FetchFailure, fetch_all
    from classcodex_targets import (
        DEFAULT_MIN_COVERAGE_RATIO,
        SkipRecord,
        build_all,
        format_coverage_report,
        format_rating_sanity,
        format_skip_summary,
        gate_and_write,
    )
    from lua_render import to_lua_compact
    from upgrade_tracks import load_track_swap
    from wowhead_stat_engine import TooltipCache, reconstruct_loadout

# Real data renders compactly to ~0.7MB (build 20260929064954, 240
# contexts); the Hero/Champion levels add ~0.26KB per context and trackSwap
# ~0.3KB, so this budget keeps plenty of headroom.
MAX_FILE_BYTES = 5 * 1024 * 1024
NAMESPACE_KEY = "ClassCodexTargets"


def render_lua(data: dict[str, Any]) -> str:
    return (
        "local addonName, ns = ...\n\n"
        "-- Generated by tools/classcodex_targets_cli.py. Do not edit manually.\n"
        f"ns.{NAMESPACE_KEY} = " + to_lua_compact(data) + "\n"
    )


def write_addon_file(data: dict[str, Any], path: Path) -> int:
    text = render_lua(data)
    size = len(text.encode("utf-8"))
    if size > MAX_FILE_BYTES:
        raise ValueError(f"classcodex targets file is {size} bytes, over the {MAX_FILE_BYTES} byte limit")
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_bytes(text.encode("utf-8"))
    tmp.replace(path)
    return size


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--simc-bin", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=Path("StatVerdict/Data/Generated/SV_ClassCodexTargets.lua"))
    parser.add_argument(
        "--min-coverage-ratio",
        type=float,
        default=DEFAULT_MIN_COVERAGE_RATIO,
        help="refuse to overwrite --out if the new run covers fewer than this fraction of its "
        "spec/goal/hero-talent contexts (pass 0 to accept a deliberate drop)",
    )
    parser.add_argument(
        "--allow-missing-track-levels",
        action="store_true",
        help="write the file even when the upgrade-track tables could not be fetched (the addon then cannot show "
        "Champion / Hero items for the lower tiers); without it the run refuses and the old file stays",
    )
    args = parser.parse_args(argv)

    try:
        fetched = fetch_all()
    except FetchFailure as exc:
        print(f"Refusing to write: {exc}", file=sys.stderr)
        return 1

    specs = build(fetched.sources)
    skips: list[SkipRecord] = []
    # Gear-only Wowhead fallback, used only for specs SimC cannot initialise
    # at all; an unreachable Wowhead just skips those combos (reported below).
    wowhead_reconstruct = functools.partial(reconstruct_loadout, cache=TooltipCache())
    # Myth -> Hero / Champion 6/6 bonus-id swap from the game's DB2 tables
    # (None when wago.tools is unreachable: then no per-track levels).
    track_swap = load_track_swap(specs)
    if track_swap is None and not args.allow_missing_track_levels:
        # Without the swap table every tier shows Myth items: worse than the file already in place.
        print("Refusing to write: the upgrade-track tables could not be fetched, so the data would have no "
              "Champion / Hero levels. The existing file stays.", file=sys.stderr)
        return 1
    result = build_all(
        specs, args.simc_bin, skips=skips, wowhead_reconstruct=wowhead_reconstruct, track_swap=track_swap
    )
    print(format_skip_summary(skips), file=sys.stderr)
    print(format_rating_sanity(result), file=sys.stderr)
    print(format_coverage_report(result, track_swap), file=sys.stderr)
    data = {"schemaVersion": 1, "buildId": fetched.build_id, "publishedAt": fetched.published_at, **result}
    if track_swap is not None:
        # The addon swaps BiS/trinket bonus ids at runtime with trackSwap
        # (the data itself keeps the Myth ids).
        data["trackSwap"] = track_swap.swap
        data["trackItemLevels"] = track_swap.item_levels
        # The 6/6 bonus id of each track: an item the guide lists without bonus ids gets its tier's.
        data["trackTop"] = track_swap.top
    return gate_and_write(data, args.out, NAMESPACE_KEY, write_addon_file, args.min_coverage_ratio)


if __name__ == "__main__":
    raise SystemExit(main())
