#!/usr/bin/env python3
"""End-to-end entry point: fetch the live ClassCodex data (from the same
public build host the official Icy Veins / U.GG desktop app updates from),
build StatVerdict's own per-spec shape, and write it as the addon's
generated data file.

Replaces the abandoned Scraper repo (github.com/ElaNte75/Scraper), which
pulled from a third-party GitHub mirror now confirmed frozen and stale.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    from tools.live_benchmark_engine import to_lua
except ModuleNotFoundError:
    # Run as "python tools/classcodex_cli.py": sys.path[0] is tools/, not the repo root.
    from live_benchmark_engine import to_lua

try:
    from tools.classcodex_build import build
    from tools.classcodex_fetch import FetchFailure, fetch_all
except ModuleNotFoundError:
    from classcodex_build import build
    from classcodex_fetch import FetchFailure, fetch_all

MAX_FILE_BYTES = 5 * 1024 * 1024


def render_lua(data: dict[str, Any]) -> str:
    return (
        "local addonName, ns = ...\n\n"
        "-- Generated by tools/classcodex_cli.py from the live ClassCodex build. Do not edit manually.\n"
        "ns.ClassCodexLiveData = " + to_lua(data) + "\n"
    )


def write_addon_file(data: dict[str, Any], path: Path) -> int:
    text = render_lua(data)
    size = len(text.encode("utf-8"))
    if size > MAX_FILE_BYTES:
        raise ValueError(f"classcodex live data file is {size} bytes, over the {MAX_FILE_BYTES} byte limit")
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_bytes(text.encode("utf-8"))
    tmp.replace(path)
    return size


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("StatVerdict/Data/Generated/SV_ClassCodexLiveData.lua"))
    parser.add_argument("--report", action="store_true", help="print a short per-spec summary and write nothing")
    args = parser.parse_args(argv)

    try:
        fetched = fetch_all()
    except FetchFailure as exc:
        print(f"Refusing to write: {exc}", file=sys.stderr)
        return 1

    specs = build(fetched.sources)
    if not specs:
        print("No specialization produced usable data; refusing to write the addon file.", file=sys.stderr)
        return 1

    data = {
        "schemaVersion": 1,
        "buildId": fetched.build_id,
        "publishedAt": fetched.published_at,
        "specs": specs,
    }

    if args.report:
        for spec_key in sorted(specs):
            fields = specs[spec_key]
            sources = ",".join(f"{name}:{fields[name]['source']}" for name in sorted(fields))
            print(f"{spec_key}: {sources}")
        print(f"build {fetched.build_id} ({fetched.published_at}), {len(specs)} specs")
        return 0

    size = write_addon_file(data, args.out)
    print(f"Wrote {args.out} ({size} bytes, {len(specs)} specs, build {fetched.build_id})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
