#!/usr/bin/env python3
"""Fetches live ClassCodex data and writes the per-goal real stat-weight
file (SimC calculate_scale_factors), meant to run on a ~15-day cadence.

Real scale-factor sims are too slow to run every spec in one CI job, so the
workflow (.github/workflows/classcodex-stat-weights.yml) shards it: each
shard runs with `--specs <keys> --partial-out <file>`, then one merge job runs
`--merge-inputs <files>`, which applies the fail-closed write gate once."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

try:
    from tools.classcodex_build import build
    from tools.classcodex_fetch import FetchFailure, fetch_all
    from tools.classcodex_targets import (
        DEFAULT_MIN_COVERAGE_RATIO,
        SkipRecord,
        _classcodex_key_to_catalog_key,
        format_skip_summary,
        gate_and_write,
    )
    from tools.classcodex_weights import build_all_weights
    from tools.live_benchmark_engine import SPEC_BY_KEY, to_lua
except ModuleNotFoundError:
    from classcodex_build import build
    from classcodex_fetch import FetchFailure, fetch_all
    from classcodex_targets import (
        DEFAULT_MIN_COVERAGE_RATIO,
        SkipRecord,
        _classcodex_key_to_catalog_key,
        format_skip_summary,
        gate_and_write,
    )
    from classcodex_weights import build_all_weights
    from live_benchmark_engine import SPEC_BY_KEY, to_lua

MAX_FILE_BYTES = 2 * 1024 * 1024
NAMESPACE_KEY = "ClassCodexWeights"


def render_lua(data: dict[str, Any]) -> str:
    return (
        "local addonName, ns = ...\n\n"
        "-- Generated by tools/classcodex_weights_cli.py. Do not edit manually.\n"
        f"ns.{NAMESPACE_KEY} = " + to_lua(data) + "\n"
    )


def write_addon_file(data: dict[str, Any], path: Path) -> int:
    text = render_lua(data)
    size = len(text.encode("utf-8"))
    if size > MAX_FILE_BYTES:
        raise ValueError(f"classcodex weights file is {size} bytes, over the {MAX_FILE_BYTES} byte limit")
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_bytes(text.encode("utf-8"))
    tmp.replace(path)
    return size


def parse_spec_filter(raw: str | None) -> set[str] | None:
    """--specs value (comma-separated StatVerdict spec keys, e.g.
    "DEATHKNIGHT_FROST,MAGE_FIRE") -> set, or None for "all specs". Unknown
    keys are an error: a typo in a workflow shard list must not silently
    drop a spec."""
    if raw is None:
        return None
    keys = {value.strip() for value in raw.split(",") if value.strip()}
    unknown = sorted(keys - set(SPEC_BY_KEY))
    if unknown:
        raise ValueError(f"unknown spec key(s) in --specs: {', '.join(unknown)}")
    return keys


def filter_specs(
    specs: dict[str, dict[str, Any]], wanted: set[str] | None, skips: list[SkipRecord]
) -> dict[str, dict[str, Any]]:
    """Keeps only the ClassCodex specs whose StatVerdict key is in `wanted`
    (all of them when `wanted` is None); a wanted spec ClassCodex has no data
    for is recorded as a skip rather than vanishing silently."""
    if wanted is None:
        return specs
    kept = {key: fields for key, fields in specs.items() if _classcodex_key_to_catalog_key(key) in wanted}
    present = {_classcodex_key_to_catalog_key(key) for key in kept}
    for missing in sorted(wanted - present):
        skips.append(SkipRecord(missing, None, None, "spec missing from ClassCodex data"))
    return kept


def write_partial(data: dict[str, Any], skips: list[SkipRecord], path: Path) -> None:
    payload = {**data, "skips": [skip._asdict() for skip in skips]}
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=1, sort_keys=True), encoding="utf-8")


def merge_partials(paths: list[Path]) -> tuple[dict[str, Any], list[SkipRecord]]:
    """Combines shard outputs (--partial-out files) into one document. Fails
    closed (ValueError) if the shards saw different ClassCodex builds or
    overlap on a spec, since either means the shard split is wrong."""
    if not paths:
        raise ValueError("--merge-inputs needs at least one partial file")
    profiles: dict[str, Any] = {}
    skips: list[SkipRecord] = []
    build_ids: set[str] = set()
    header: dict[str, Any] = {}
    for path in paths:
        partial = json.loads(path.read_text(encoding="utf-8"))
        build_ids.add(str(partial.get("buildId")))
        header = {key: partial.get(key) for key in ("schemaVersion", "buildId", "publishedAt")}
        overlap = sorted(set(profiles) & set(partial.get("profiles") or {}))
        if overlap:
            raise ValueError(f"{path} overlaps earlier partials on: {', '.join(overlap)}")
        profiles.update(partial.get("profiles") or {})
        skips.extend(SkipRecord(**skip) for skip in partial.get("skips") or [])
    if len(build_ids) > 1:
        raise ValueError(f"partials come from different ClassCodex builds: {', '.join(sorted(build_ids))}")
    return {**header, "profiles": profiles}, skips


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--simc-bin", type=Path, help="SimulationCraft binary (required unless --merge-inputs)")
    parser.add_argument("--out", type=Path, default=Path("StatVerdict/Data/Generated/SV_ClassCodexWeights.lua"))
    parser.add_argument(
        "--min-coverage-ratio",
        type=float,
        default=DEFAULT_MIN_COVERAGE_RATIO,
        help="refuse to overwrite --out if the new run covers fewer than this fraction of its "
        "spec/goal/hero-talent contexts (pass 0 to accept a deliberate drop)",
    )
    parser.add_argument("--specs", help="only compute these comma-separated StatVerdict spec keys (one CI shard)")
    parser.add_argument(
        "--partial-out",
        type=Path,
        help="write this shard's result as JSON here instead of writing --out (merged later with --merge-inputs)",
    )
    parser.add_argument(
        "--merge-inputs",
        help="comma-separated --partial-out files to combine into --out (no fetch, no SimC)",
    )
    args = parser.parse_args(argv)

    if args.merge_inputs:
        try:
            data, skips = merge_partials([Path(p.strip()) for p in args.merge_inputs.split(",") if p.strip()])
        except (OSError, ValueError, TypeError) as exc:
            print(f"Refusing to write: {exc}", file=sys.stderr)
            return 1
        print(format_skip_summary(skips), file=sys.stderr)
        return gate_and_write(data, args.out, NAMESPACE_KEY, write_addon_file, args.min_coverage_ratio)

    if args.simc_bin is None:
        parser.error("--simc-bin is required unless --merge-inputs is given")
    try:
        wanted = parse_spec_filter(args.specs)
    except ValueError as exc:
        parser.error(str(exc))

    try:
        fetched = fetch_all()
    except FetchFailure as exc:
        print(f"Refusing to write: {exc}", file=sys.stderr)
        return 1

    skips: list[SkipRecord] = []
    specs = filter_specs(build(fetched.sources), wanted, skips)
    result = build_all_weights(specs, args.simc_bin, skips=skips)
    print(format_skip_summary(skips), file=sys.stderr)
    data = {"schemaVersion": 1, "buildId": fetched.build_id, "publishedAt": fetched.published_at, **result}
    if args.partial_out:
        # A shard never gates on its own: an all-skipped shard (e.g. healers,
        # whose SimC healing model may yield no usable HPS scale factors) is a
        # valid partial. The merge step applies the fail-closed gate once,
        # over the combined result.
        write_partial(data, skips, args.partial_out)
        print(f"Wrote partial {args.partial_out} ({len(data['profiles'])} specs)")
        return 0
    return gate_and_write(data, args.out, NAMESPACE_KEY, write_addon_file, args.min_coverage_ratio)


if __name__ == "__main__":
    raise SystemExit(main())
