#!/usr/bin/env python3
"""Fetches live ClassCodex data and writes the per-goal real stat-weight
file (SimC calculate_scale_factors), meant to run on a ~15-day cadence."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    from tools.classcodex_build import build
    from tools.classcodex_fetch import FetchFailure, fetch_all
    from tools.classcodex_weights import build_all_weights
    from tools.live_benchmark_engine import to_lua
except ModuleNotFoundError:
    from classcodex_build import build
    from classcodex_fetch import FetchFailure, fetch_all
    from classcodex_weights import build_all_weights
    from live_benchmark_engine import to_lua

MAX_FILE_BYTES = 2 * 1024 * 1024


def render_lua(data: dict[str, Any]) -> str:
    return (
        "local addonName, ns = ...\n\n"
        "-- Generated by tools/classcodex_weights_cli.py. Do not edit manually.\n"
        "ns.ClassCodexWeights = " + to_lua(data) + "\n"
    )


def write_addon_file(data: dict[str, Any], path: Path) -> int:
    text = render_lua(data)
    size = len(text.encode("utf-8"))
    if size > MAX_FILE_BYTES:
        raise ValueError(f"classcodex weights file is {size} bytes, over the {MAX_FILE_BYTES} byte limit")
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_bytes(text.encode("utf-8"))
    tmp.replace(path)
    return size


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--simc-bin", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=Path("StatVerdict/Data/Generated/SV_ClassCodexWeights.lua"))
    args = parser.parse_args(argv)

    try:
        fetched = fetch_all()
    except FetchFailure as exc:
        print(f"Refusing to write: {exc}", file=sys.stderr)
        return 1

    specs = build(fetched.sources)
    result = build_all_weights(specs, args.simc_bin)
    data = {"schemaVersion": 1, "buildId": fetched.build_id, "publishedAt": fetched.published_at, **result}
    if not data["profiles"]:
        print("No specialization produced usable weights; refusing to write the addon file.", file=sys.stderr)
        return 1
    size = write_addon_file(data, args.out)
    print(f"Wrote {args.out} ({size} bytes, {len(data['profiles'])} specs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
