#!/usr/bin/env python3
"""Writes StatVerdict/Data/Generated/SV_ItemSources.lua: where each item of the season's dungeons
and raids drops, for the "Where to find" lines of the Best in Slot and Ranked Trinkets tooltips.

The data is Blizzard's own Adventure Journal (tools/blizzard_item_pool.py -> tools/data/blizzard_item_pool.json),
so only items the journal lists get a line; nothing is guessed. Great Vault, crafting and the Catalyst are
not item-specific there and are left out.

    python tools/item_sources.py [--pool tools/data/blizzard_item_pool.json] [--out StatVerdict/Data/Generated/SV_ItemSources.lua]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

# The raids of the season; every other non-dungeon journal instance (world bosses, delves) is named
# without a kind, because the journal does not say which it is.
KNOWN_RAIDS = frozenset({"The Voidspire", "The Dreamrift", "March on Quel'Danas"})
KIND_CODE = {"dungeon": "D", "raid": "R"}
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_POOL = ROOT / "tools" / "data" / "blizzard_item_pool.json"
DEFAULT_OUT = ROOT / "StatVerdict" / "Data" / "Generated" / "SV_ItemSources.lua"


def source_kind(source: dict[str, Any]) -> str:
    """"D" dungeon, "R" raid, "" when the journal does not say (world boss, delve)."""
    if source.get("kind") == "dungeon":
        return "D"
    if source.get("kind") == "raid" and source.get("instance") in KNOWN_RAIDS:
        return "R"
    return ""


def build_sources(pool: dict[str, Any]) -> dict[int, list[list[str]]]:
    """{item id: [[instance, boss, kind], ...]} (a repeated source once, in journal order)."""
    out: dict[int, list[list[str]]] = {}
    for item_id, row in (pool.get("items") or {}).items():
        seen: list[list[str]] = []
        for source in row.get("sources") or []:
            instance, boss = str(source.get("instance") or ""), str(source.get("encounter") or "")
            if not instance or not boss:
                continue
            entry = [instance, boss, source_kind(source)]
            if entry not in seen:
                seen.append(entry)
        if seen:
            out[int(item_id)] = seen
    return out


def render_lua(sources: dict[int, list[list[str]]], season_tier: Any = None) -> str:
    rows = []
    for item_id in sorted(sources):
        entries = ",".join("{" + ",".join(json.dumps(part, ensure_ascii=False) for part in entry) + "}"
                           for entry in sources[item_id])
        rows.append(f"[{item_id}]={{{entries}}}")
    return (
        "local addonName, ns = ...\n\n"
        "-- Generated by tools/item_sources.py from the Adventure Journal. Do not edit manually.\n"
        "-- [item id] = { {instance, boss, kind}, ... }; kind D dungeon, R raid, \"\" unknown.\n"
        "ns.ItemSources = {" + ",".join(rows) + "}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--pool", type=Path, default=DEFAULT_POOL)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)
    pool = json.loads(args.pool.read_text(encoding="utf-8"))
    sources = build_sources(pool)
    if not sources:
        print("The pool lists no drop sources: nothing written.")
        return 1
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_lua(sources), encoding="utf-8")
    print(f"Wrote {args.out} ({len(sources)} items)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
